### ISSUE TITLE
Redirect loop after authenticated

### ISSUE THREAD

**Issue by vhorvath001** [penn-state-dance-marathon/python3-saml-django#25]
Good morning,

I could successfully authenticate against Azure AD but I got to to a redirect loop unfortunately.

**logs**
```
July 26, 2022 - 10:52:27
Django version 3.2.13, using settings 'management_app.settings'
Starting development server at http://127.0.0.1:7000/
Quit the server with CONTROL-C.
[26/Jul/2022 10:52:38] "GET / HTTP/1.1" 302 0
[26/Jul/2022 10:52:38] "GET /saml/login?next=/ HTTP/1.1" 302 0
[26/Jul/2022 10:52:38] "GET / HTTP/1.1" 302 0
[26/Jul/2022 10:52:38] "GET /saml/login?next=/ HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "POST /saml/acs/ HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "GET / HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "GET /saml/login?next=/ HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "POST /saml/acs/ HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "GET / HTTP/1.1" 302 0
[26/Jul/2022 10:52:50] "GET /saml/login?next=/ HTTP/1.1" 302 0
...
```

**config**
```
INSTALLED_APPS = [
    ...
    'django_saml',
]

LOGIN_URL = '/saml/login'
AUTHENTICATION_BACKENDS = [
    'django_saml.backends.SamlUserBackend',
    'django.contrib.auth.backends.ModelBackend'
]
SAML_SP = {
    "entityId": "http://localhost:7000/saml/metadata/",
    "assertionConsumerService": {
        "url": "http://localhost:7000/saml/acs/",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
        "url": "http://localhost:7000/saml/sls/",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
}
SAML_BASE_DIRECTORY = os.path.join(BASE_DIR, 'management_app')
SAML_IDP = {
    "entityId": "https://sts.windows.net/8d***********b6/",
    "singleSignOnService": {
        "url": "https://login.microsoftonline.com/8d***********b6/saml2",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "singleLogoutService": {
        "url": "https://login.microsoftonline.com/8d***********b6/saml2",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "x509cert":
"MIID3zCCAsegAwIBAgIJALljhiy5NzzfMA0GCSqGSIb3DQEBCwUAMIGFMQswCQYDVQQGEwJVSzES"
...
}
SAML_IDP_FILE = os.path.join(BASE_DIR, 'management_app/azure-ad-metadata.xml')
SAML_IDP_URL = 'https://sts.windows.net/8d***********b6/'
SAML_DEBUG = True
SAML_CREATE_USER = True
SAML_USERNAME_ATTR = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'
SAML_LOGIN_REDIRECT = '/dashboard'
SAML_SECURITY = {
    "nameIdEncrypted": False,
    "authnRequestsSigned": False,
    "logoutRequestSigned": False,
    "logoutResponseSigned": False,
    "signMetadata": False,
    "wantMessagesSigned": False,
    "wantAssertionsSigned": False,
    "wantNameId": False,
    "wantNameIdEncrypted": False,
    "wantAssertionsEncrypted": False,
    "signatureAlgorithm": "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
    "digestAlgorithm": "http://www.w3.org/2000/09/xmldsig#sha1"
}
```

**urls.py**
```
urlpatterns = [
    path('saml/',  include('django_saml.urls')),
    ...
]
```

I am just wondering if I can switch on more debug so I can see what is going on exactly? 
Do you know by any chance where the problem comes from? I presume the token is sent back to my local SP (python3-saml-django) but it didn't accept it so it wanted to authenticate again but the cookie already exists so the same is sent back immediately to python3-saml-django which didn't accept it again and so on. Something like that?

Thank you!

**Comment by ngearhart** [comment]
Usually, a redirect loop is the result of Django still not thinking you're logged in. I would recommend confirming this using your browser dev tools with "preserve logs" enabled to see where you go. I am guessing it will be Dashboard -> SAML login -> SSO -> Dashboard -> Back to SAML login. Another way to confirm this would be to remove the login requirement from the Dashboard view and see if it stops redirecting.

If you confirm that is the case, check to see if the correct User model exists for whoever you are logging in as. Since you have `SAML_CREATE_USER = True`, try deleting this user and see if it recreates when you try to log in.

If that also exists, let me know and we can keep troubleshooting.

**Comment by ngearhart** [comment]
> I am just wondering if I can switch on more debug so I can see what is going on exactly?

Unfortunately there isn't some specific switch you can turn on to make this troubleshooting process easier, but I'm here to help walk you through the right places to look.

**Comment by vhorvath001** [comment]
Hi Noah, 

Thank you for your help!
I think that's the case, please see the image attached.

![image](https://user-images.githubusercontent.com/16352140/181041027-296b3141-5ddb-436d-995a-0201dc2d4671.png)

The user was created in the AUTH_USER table. I deleted it but it was recreated when I tried to log in next time.
Thanks again!

**Comment by vhorvath001** [comment]
BTW I could get the SAML AuthRequest but I don't know where the SAML response can be extracted from.
```
<samlp:AuthnRequest
  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
  xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
  ID="ONELOGIN_52258b5aaf24fe09f2e71cbb0b465baa7bd40a99"
  Version="2.0"
  IssueInstant="2022-07-26T14:46:14Z"
  Destination="https://login.microsoftonline.com/8d469bba-ae86-4fe1-a36d-fa9d26ec8ab6/saml2"
  ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  AssertionConsumerServiceURL="http://localhost:7000/saml/acs/">
    <saml:Issuer>http://localhost:7000/saml/metadata/</saml:Issuer>
    <samlp:NameIDPolicy
        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
        AllowCreate="true" />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

**Comment by ngearhart** [comment]
Yeah those network logs are describing exactly what I thought - Django isn't actually logging you in. I am not completely sure what's up here, but it's likely a misconfiguration.

Could you create a custom backend that inherits from `django_saml.backends.SamlUserBackend` and override the `configure_user` method? Something like:

```
class TestUserBackend(SamlUserBackend):
    def configure_user(self, session_data, user, ignore_fields=None):
        print(user)
        return super().configure_user(session_data, user, ignore_fields)
```

Then set `AUTHENTICATION_BACKENDS = ('your.package.TestUserBackend',)`

**Comment by ngearhart** [comment]
Also, if you have your Django server logs during the login, that would be useful too (don't forget to censor sensitive info 🙂)

**Comment by ngearhart** [comment]
Another thing that is not super clear in the README - you only need 1 of `SAML_IDP`, `SAML_IDP_FILE`, and `SAML_IDP_URL` in your settings. I would recommend `SAML_IDP_URL` because that will automatically update from the IDP.

**Comment by vhorvath001** [comment]
Thanks for the hints!
Now I set only the `SAML_IDP_URL`.
Unfortunately I dont have more server logs than I added to the original post. I set the `root` logger to DEBUG but still nothing is logged I am afraid.
I printed the user, the printed username matches the User Principal Name set in Azure AD.
I can debug the code though and I can extract more information if needed.

**Comment by ngearhart** [comment]
Let me know how that goes, unfortunately I do not have any more ideas at the moment.

**Comment by vhorvath001** [comment]
No problem, thank you for your help!
I think the problem is in my config but ... would to be good to know where. :) If I found out then I'll let you know!
Thanks again!

**Comment by ngearhart** [comment]
I have a thought - you have `SAML_LOGIN_REDIRECT` set to `/dashboard` but when you login, you are sent to `/`. This could be a problem! Check your Azure AD settings to see where the redirect target is - if the IDP provides a redirect target, `SAML_LOGIN_REDIRECT` is ignored.

**Comment by vhorvath001** [comment]
Thanks for the hint! 
I am not sure where I could check this redirect target in Azure AD. I can see the Reply URL but the Assertion Consumer Service URL has to be added there (https://localhost:8000/saml/acs/). I changed the `SAML_LOGIN_REDIRECT `'/'` but no success.
I found the following page where the author deals with a similar problem: https://blogs.aaddevsup.xyz/2019/07/infinite-redirect-between-openid-connect-application-and-azure-ad/
So I quickly setup SSL and changed what need to be changed but the infinite loop didn't go away. It is pretty frustrating as I am not sure what else I can do.
Nevertheless thank you for your help! 
It isn't a python3-saml-django issue, shall I close this ticket?

**Comment by ngearhart** [comment]
You can keep the ticket open, I still think it is an issue of Django not logging you in correctly.

**Comment by vhorvath001** [comment]
Obviously it was my mistake... :) It seems that the issue was that I use custom permission which Azure AD doesn't send so Django rejects it and redirects it to log in. However the cookie is there so the same user will be logged in automatically which Django rejects, etc.

Do you know by any chance how I could display the Azure AD login page if the user doesn't have the permission? Thanks!

**Comment by ngearhart** [comment]
Glad to hear you made some progress!

**Future users who face this problem**: The problem was that the target view had extra permissions that the default created user didn't have, resulting in a redirect back to login. However, since the user was successfully logged in, there was an infinite redirect loop.

The recommended way to solve this generally is to use a [custom 403 page](https://docs.djangoproject.com/en/4.0/ref/views/#the-403-http-forbidden-view) instead of a redirect. [Azure AD out of the box does not support showing a custom error message](https://stackoverflow.com/a/71568850), so it is not obvious how to tell the user they do not have permission.

A possible option is to have a "5-second" view - upon having no permission, you get redirected to a page that says "Sorry, you must login using an account that has permission to view this page. You will be logged out and redirected in 5 seconds..." or similar. **Make sure to log the user out in this view** or it will be an infinite loop again. You will have to not only log out of Django but also call the SLS endpoint on AD.

**Comment by vhorvath001** [comment]
Thanks for the hint and all the help!
