### ISSUE TITLE
Provide FriendlyName when available ?

### ISSUE THREAD

**Issue by bryan-brancotte** [penn-state-dance-marathon/python3-saml-django#28]
Hi,

My `SAML_ATTR_MAP` was built the friendlyName of the attributes, but I ended with a KeyError when searching for the `SAML_USERNAME_ATTR` (which was `username`) in https://github.com/penn-state-dance-marathon/python3-saml-django/blob/57ef6e4014beb93f59e46c4505fa13f6c527cc5c/django_saml/backends.py#L19

I found out that the saml_acs created the session_data with only the attribute names, not the friendly attribute names
https://github.com/penn-state-dance-marathon/python3-saml-django/blob/57ef6e4014beb93f59e46c4505fa13f6c527cc5c/django_saml/views.py#L109

I had to change my `SAML_ATTR_MAP` this way

```diff
 SAML_ATTR_MAP = [
-    ('uid', 'username'),
-    ('givenName', 'first_name'),
-    ('sn', 'last_name'),
-    ('mail', 'email'),
+    ('urn:oid:0.9.2342.19200300.100.1.1', 'username'),
+    ('urn:oid:2.5.4.42', 'first_name'),
+    ('urn:oid:2.5.4.4', 'last_name'),
+    ('urn:oid:0.9.2342.19200300.100.1.3', 'email'),
 ]
+ SAML_USERNAME_ATTR = [k for k, v in SAML_ATTR_MAP if v == 'username'][0]
```

Have I forgot something to indicate that we should load the FriendlyName and not the Name ?

A simple patch would be to build the session_data with both the attributes, and the attribute with there friendly name.

in https://github.com/penn-state-dance-marathon/python3-saml-django/blob/57ef6e4014beb93f59e46c4505fa13f6c527cc5c/django_saml/views.py#L109
```py
    user = auth.authenticate(
        session_data=dict(**saml_auth.get_friendlyname_attributes(), **saml_auth.get_attributes())
    )
```
I can create the PR if you want.

Best regards

**Comment by ngearhart** [comment]
Can you clarify why you need to reference attributes by friendly name?
SAML attributes should usually be accessed by their regular name.

Here is an example of an attribute that has friendly name "givenName" but should be accessed by "urn:oid:2.5.4.42".
```
<Attribute
    NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
    Name="urn:oid:2.5.4.42"
    FriendlyName="givenName">
   <AttributeValue>Scott</AttributeValue>
</Attribute>
```
([Source](https://shibboleth.atlassian.net/wiki/spaces/CONCEPT/pages/928645122/SAMLAttributeNaming))

I would recommend looking at your SAML responses if you are getting a KeyError to find the username attribute.

One more thing - can you explain the motivation behind the `SAML_USERNAME_ATTR = [k for k, v in SAML_ATTR_MAP if v == 'username'][0]` instead of just `SAML_USERNAME_ATTR = 'urn:oid:0.9.2342.19200300.100.1.1'`? Although it might be more 'dry', it is way less readable than the alternative.

**Comment by bryan-brancotte** [comment]
Hi,

The `SAML_USERNAME_ATTR = [ k for k, v .....` is the result of me testing why I can't use the friendly name, and should have not arrived here. 

The example in the documentation for `SAML_ATTR_MAP` are provided with friendly name, not with the regular name [source](https://github.com/penn-state-dance-marathon/python3-saml-django/blob/master/README.md?plain=1#L125) I assumed that "normally" I should have used the friendly name, and that I missed something.

> SAML attributes should usually be accessed by their regular name.

I understand this point now, my bad. Could you update the README.md to provide an example for SAML_USERNAME_ATTR with regular name ?

**Comment by ngearhart** [comment]
I see your point. I will update the README to be more clear. Thank you for submitting an issue!

**Comment by ngearhart** [comment]
I just added this to the README: https://github.com/penn-state-dance-marathon/python3-saml-django#a-note-about-attributes

Let me know if you are interested in further clarification, otherwise I will close this issue.

**Comment by bryan-brancotte** [comment]
Thanks for your edition, I would have helped me and will help futur user in my situation.
Thanks again :)
