### ISSUE TITLE
auth.authenticate(session_data=saml_auth.get_attributes()) fails

### ISSUE THREAD

**Issue by nesazeri** [penn-state-dance-marathon/python3-saml-django#6]
'uid'
Traceback (most recent call last):
  File "D:\home\python364x64\lib\site-packages\django_saml\views.py", line 121, in saml_acs
    user = auth.authenticate(session_data=saml_auth.get_attributes())
  File "D:\home\python364x64\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "D:\home\python364x64\lib\site-packages\django_saml\backends.py", line 16, in authenticate
    username = session_data[settings.SAML_USERNAME_ATTR][0]
KeyError: 'uid'
Bad Request: /saml/acs/

log of: saml_auth.get_attributes()
{'http://schemas.microsoft.com/identity/claims/tenantid': ['b989f104-d41b-4f40-b814-1a3bfee7dbc7'], 'http://schemas.microsoft.com/identity/claims/objectidentifier': ['593bef0b-693a-4536-b5d0-1c24da9da6cc'], 'http://schemas.microsoft.com/identity/claims/displayname': ['SAMLTEST1'], 'http://schemas.microsoft.com/identity/claims/identityprovider': ['https://sts.windows.net/b989f104-d41b-4f40-b814-1a3bfee7dbc7/'], 'http://schemas.microsoft.com/claims/authnmethodsreferences': ['urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'], 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname': ['SAMLTEST1'], 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname': ['SAMLTEST1'], 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name': ['SAMLTEST1@TEST.onmicrosoft.com']}

**Comment by voyc-jean** [comment]
Your SAML IDP doesn't have 'uid' as part of its schema. You need to set SAML_USERNAME_ATTR in your Django settings to whichever attribute you want to use to look up your Django users. For example: `SAML_USERNAME_ATTR = 'name'`

If you want to associate users with an attribute such as email address, you'll need to configure this on your IDP so it includes `mail` in the attributes. [See Azure's documentation.](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-claims-customization)

**Comment by nesazeri** [comment]
thanks
